
# yaml-language-server: $schema=./values.schema.json

global:
  domain: null
  imagePullSecret: {}
srv:
  bindings:
    db:
      fromSecret: null
    messaging:
      serviceInstanceName: event-mesh
  image:
    repository: <your-container-registry>/cap-hana-swapi-srv
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      cpu: 500m
      ephemeral-storage: 1G
      memory: 500M
  health_check:
    liveness:
      path: /
    readiness:
      path: /
hana_deployer:
  image:
    repository: <your-container-registry>/cap-hana-swapi-hana-deployer
    tag: latest
  bindings:
    hana:
      fromSecret: null
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
event_mesh:
  serviceOfferingName: enterprise-messaging
  servicePlanName: default
  config: event-mesh.json
