
# yaml-language-server: $schema=./values.root.schema.json

global:
  domain: c-18e23d2.kyma.ondemand.com
  imagePullSecret:
    name: regcred
srv:
  bindings:
    db:
      fromSecret: starwars
  image:
    repository: ghcr.io/sap-samples/cap-hana-swapi-srv
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      cpu: 500m
      ephemeral-storage: 1G
      memory: 500M
  health_check:
    liveness:
      path: /
    readiness:
      path: /
hana_deployer:
  image:
    repository: ghcr.io/sap-samples/cap-hana-swapi-db
    tag: latest
  bindings:
    hana:
      fromSecret: starwars
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
